title: The coding adventure of aaron kenny
author: Aaron Kehinde Adetunmbi
email: adetunmbikenny@gmail.com
description: > 
   The coding adventure of aaron kenny, i'm going to be talking a lot about myself
   in this github page blog. Poke around and make yaself at home.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kenneropia # DO NOT include the @ character, or else the build will fail!

theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
